apiVersion: v1
kind: Pod
metadata:
  name: node-app
  labels:
    app: node-redis
spec:
  containers:
  - name: node-app
    image: node-app:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: data
      mountPath: /data
      readOnly: false
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: redis-data